POST http://0.0.0.0:8080/v1/guilds
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiNmY2OTlkNjAtYjI2Mi00YTFlLTliMGEtZjMxNzgxOGRmNzNjIn0.6jPzy0sF7Z5MnUIkHsQYhx7yzVRmxQoNJ3wY3wO9uJk

{
  "guild": {
    "name": "rad dads2",
    "description": "over the world",
    "ownerIds": ["6f699d60-b262-4a1e-9b0a-f317818df73c"]
  }
}
