GET http://0.0.0.0:8080/v1/guilds/1f1f6480-e998-43da-a436-fd9f60cae672
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiNjJiMjEyOWItZDU1Zi00NDc2LWIyYjgtMGY1YjU3MThmNTZhIn0.vgVS9_DYkHjz3nyRFCILNBxwvQOvmW6DO6Lr9OCQ_Kg


