GET http://0.0.0.0:8080/v1/players/2d14bea4-34dc-4805-bcfe-10d58db8113d
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiNjJiMjEyOWItZDU1Zi00NDc2LWIyYjgtMGY1YjU3MThmNTZhIn0.vgVS9_DYkHjz3nyRFCILNBxwvQOvmW6DO6Lr9OCQ_Kg
